# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-30 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('spec', models.CharField(default='500g', max_length=20, verbose_name='规格')),
                ('picture', models.ImageField(upload_to='static/upload/goods', verbose_name='商品图片')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='品类名')),
                ('desc', models.CharField(max_length=200, verbose_name='品类描述')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('upwd', models.CharField(max_length=32, verbose_name='密码')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('uemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType'),
        ),
    ]
